import React, { useState, useEffect } from "react";
import { LucideIcon } from "../LucideIcon";

export const SeoTools: React.FC = () => {
  const [activeTab, setActiveTab] = useState<"meta" | "robots" | "sitemap">("meta");
  const [outputText, setOutputText] = useState<string>("");

  // Meta Tag Generator state
  const [metaTitle, setMetaTitle] = useState<string>("My Awesome Multi-Tool SaaS App");
  const [metaDesc, setMetaDesc] = useState<string>("An online enterprise suite of free utilities, QR code generators, image converters, and developer helpers.");
  const [metaKeywords, setMetaKeywords] = useState<string>("tools, online tools, free qr generator, image compressor");
  const [metaAuthor, setMetaAuthor] = useState<string>("QRToolkit Core");
  const [metaUrl, setMetaUrl] = useState<string>("https://qrtoolkit.site");
  const [metaEnableOg, setMetaEnableOg] = useState<boolean>(true);
  const [metaEnableTwitter, setMetaEnableTwitter] = useState<boolean>(true);

  // Robots.txt Generator state
  const [robotsSitemap, setRobotsSitemap] = useState<string>("https://qrtoolkit.site/sitemap.xml");
  const [robotsUserAgent, setRobotsUserAgent] = useState<string>("*");
  const [robotsDisallowed, setRobotsDisallowed] = useState<string>("/api/\n/admin/");

  // Sitemap state
  const [sitemapUrls, setSitemapUrls] = useState<string>(
    "https://qrtoolkit.site/\nhttps://qrtoolkit.site/image-compressor\nhttps://qrtoolkit.site/qr-code-generator\nhttps://qrtoolkit.site/password-generator\nhttps://qrtoolkit.site/developer-tools"
  );

  useEffect(() => {
    generateOutputs();
  }, [activeTab, metaTitle, metaDesc, metaKeywords, metaAuthor, metaUrl, metaEnableOg, metaEnableTwitter, robotsSitemap, robotsUserAgent, robotsDisallowed, sitemapUrls]);

  const generateOutputs = () => {
    if (activeTab === "meta") {
      let code = `<!-- HTML Primary Meta Tags -->\n`;
      code += `<title>${metaTitle}</title>\n`;
      code += `<meta name="title" content="${metaTitle}">\n`;
      code += `<meta name="description" content="${metaDesc}">\n`;
      if (metaKeywords) code += `<meta name="keywords" content="${metaKeywords}">\n`;
      if (metaAuthor) code += `<meta name="author" content="${metaAuthor}">\n`;
      code += `<link rel="canonical" href="${metaUrl}">\n\n`;

      if (metaEnableOg) {
        code += `<!-- Open Graph / Facebook / LinkedIn -->\n`;
        code += `<meta property="og:type" content="website">\n`;
        code += `<meta property="og:url" content="${metaUrl}">\n`;
        code += `<meta property="og:title" content="${metaTitle}">\n`;
        code += `<meta property="og:description" content="${metaDesc}">\n`;
        code += `<meta property="og:image" content="${metaUrl}/cover.png">\n\n`;
      }

      if (metaEnableTwitter) {
        code += `<!-- Twitter Cards -->\n`;
        code += `<meta property="twitter:card" content="summary_large_image">\n`;
        code += `<meta property="twitter:url" content="${metaUrl}">\n`;
        code += `<meta property="twitter:title" content="${metaTitle}">\n`;
        code += `<meta property="twitter:description" content="${metaDesc}">\n`;
        code += `<meta property="twitter:image" content="${metaUrl}/cover.png">\n`;
      }

      setOutputText(code);
    } 
    else if (activeTab === "robots") {
      let code = `# Robots.txt file generated by QRToolkit.site\n\n`;
      code += `User-agent: ${robotsUserAgent}\n`;
      
      const lines = robotsDisallowed.split("\n");
      lines.forEach((line) => {
        if (line.trim()) {
          code += `Disallow: ${line.trim()}\n`;
        }
      });
      code += `Allow: /\n\n`;

      if (robotsSitemap) {
        code += `# Sitemap Locator\n`;
        code += `Sitemap: ${robotsSitemap}\n`;
      }

      setOutputText(code);
    } 
    else if (activeTab === "sitemap") {
      const today = new Date().toISOString().split("T")[0];
      let code = `<?xml version="1.0" encoding="UTF-8"?>\n`;
      code += `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n`;

      const lines = sitemapUrls.split("\n");
      lines.forEach((line) => {
        const url = line.trim();
        if (url) {
          code += `  <url>\n`;
          code += `    <loc>${url}</loc>\n`;
          code += `    <lastmod>${today}</lastmod>\n`;
          code += `    <changefreq>daily</changefreq>\n`;
          code += `    <priority>0.8</priority>\n`;
          code += `  </url>\n`;
        }
      });

      code += `</urlset>`;
      setOutputText(code);
    }
  };

  const copyOutput = () => {
    navigator.clipboard.writeText(outputText);
  };

  const downloadTextFile = () => {
    const filename = activeTab === "meta" ? "meta-tags.html" : activeTab === "robots" ? "robots.txt" : "sitemap.xml";
    const mime = activeTab === "meta" ? "text/html" : activeTab === "robots" ? "text/plain" : "text/xml";
    
    const blob = new Blob([outputText], { type: mime });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.download = filename;
    link.href = url;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div className="bg-white/80 dark:bg-slate-900/80 backdrop-blur-md rounded-3xl border border-slate-200 dark:border-slate-800 p-6 md:p-8 shadow-xl">
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
        
        {/* Navigation Sidebar */}
        <div className="lg:col-span-3 flex lg:flex-col gap-1.5 overflow-x-auto lg:overflow-visible pb-3 lg:pb-0 border-b lg:border-b-0 lg:border-r border-slate-100 dark:border-slate-800/60 lg:pr-6 shrink-0">
          {[
            { id: "meta", label: "Meta Tag Builder", icon: "Search" },
            { id: "robots", label: "Robots.txt Editor", icon: "FileText" },
            { id: "sitemap", label: "XML Sitemap Maker", icon: "Grid" }
          ].map((tab) => (
            <button
              key={tab.id}
              onClick={() => {
                setActiveTab(tab.id as any);
              }}
              className={`flex items-center gap-3 py-2.5 px-4 rounded-xl text-sm font-semibold transition-all shrink-0 cursor-pointer w-full text-left ${
                activeTab === tab.id
                  ? "bg-slate-900 dark:bg-slate-50 text-white dark:text-slate-900 shadow-md"
                  : "hover:bg-slate-100 dark:hover:bg-slate-950 text-slate-600 dark:text-slate-400"
              }`}
            >
              <LucideIcon name={tab.icon} size={16} />
              <span>{tab.label}</span>
            </button>
          ))}
        </div>

        {/* Form Inputs Workspace Column */}
        <div className="lg:col-span-4 space-y-4">
          <h4 className="text-sm font-bold uppercase tracking-wide text-slate-400">Configure parameters</h4>
          
          {activeTab === "meta" && (
            <div className="space-y-3">
              <div>
                <span className="text-xs font-semibold text-slate-500">Site Title</span>
                <input
                  type="text"
                  value={metaTitle}
                  onChange={(e) => setMetaTitle(e.target.value)}
                  className="w-full mt-1 px-3 py-2 border border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-950 text-slate-800 dark:text-slate-200 text-sm rounded-xl focus:outline-none"
                />
              </div>

              <div>
                <span className="text-xs font-semibold text-slate-500">Meta Description</span>
                <textarea
                  value={metaDesc}
                  onChange={(e) => setMetaDesc(e.target.value)}
                  rows={3}
                  className="w-full mt-1 px-3 py-2 border border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-950 text-slate-800 dark:text-slate-200 text-sm rounded-xl focus:outline-none resize-none"
                />
              </div>

              <div>
                <span className="text-xs font-semibold text-slate-500">Keywords (Comma separated)</span>
                <input
                  type="text"
                  value={metaKeywords}
                  onChange={(e) => setMetaKeywords(e.target.value)}
                  className="w-full mt-1 px-3 py-2 border border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-950 text-slate-800 dark:text-slate-200 text-sm rounded-xl focus:outline-none"
                />
              </div>

              <div>
                <span className="text-xs font-semibold text-slate-500">Canonical Website URL</span>
                <input
                  type="text"
                  value={metaUrl}
                  onChange={(e) => setMetaUrl(e.target.value)}
                  className="w-full mt-1 px-3 py-2 border border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-950 text-slate-800 dark:text-slate-200 text-sm rounded-xl focus:outline-none"
                />
              </div>

              <div className="flex gap-4 pt-1.5">
                <label className="flex items-center gap-2 text-xs text-slate-600 dark:text-slate-400 select-none cursor-pointer">
                  <input
                    type="checkbox"
                    checked={metaEnableOg}
                    onChange={(e) => setMetaEnableOg(e.target.checked)}
                    className="w-4 h-4 rounded border-slate-300 text-blue-600 focus:ring-blue-500"
                  />
                  <span>Facebook OG</span>
                </label>
                <label className="flex items-center gap-2 text-xs text-slate-600 dark:text-slate-400 select-none cursor-pointer">
                  <input
                    type="checkbox"
                    checked={metaEnableTwitter}
                    onChange={(e) => setMetaEnableTwitter(e.target.checked)}
                    className="w-4 h-4 rounded border-slate-300 text-blue-600 focus:ring-blue-500"
                  />
                  <span>Twitter Card</span>
                </label>
              </div>
            </div>
          )}

          {activeTab === "robots" && (
            <div className="space-y-3">
              <div>
                <span className="text-xs font-semibold text-slate-500">User Agent Crawlers</span>
                <input
                  type="text"
                  value={robotsUserAgent}
                  onChange={(e) => setRobotsUserAgent(e.target.value)}
                  placeholder="*"
                  className="w-full mt-1 px-3 py-2 border border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-950 text-slate-800 dark:text-slate-200 text-sm rounded-xl focus:outline-none"
                />
              </div>

              <div>
                <span className="text-xs font-semibold text-slate-500">Disallowed Paths (one per line)</span>
                <textarea
                  value={robotsDisallowed}
                  onChange={(e) => setRobotsDisallowed(e.target.value)}
                  rows={4}
                  className="w-full mt-1 px-3 py-2 border border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-950 text-slate-800 dark:text-slate-200 text-sm rounded-xl focus:outline-none resize-none font-mono"
                />
              </div>

              <div>
                <span className="text-xs font-semibold text-slate-500">Sitemap URL Locator</span>
                <input
                  type="text"
                  value={robotsSitemap}
                  onChange={(e) => setRobotsSitemap(e.target.value)}
                  className="w-full mt-1 px-3 py-2 border border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-950 text-slate-800 dark:text-slate-200 text-sm rounded-xl focus:outline-none"
                />
              </div>
            </div>
          )}

          {activeTab === "sitemap" && (
            <div className="space-y-3">
              <div>
                <span className="text-xs font-semibold text-slate-500">Sitemap Site URLs (one per line)</span>
                <textarea
                  value={sitemapUrls}
                  onChange={(e) => setSitemapUrls(e.target.value)}
                  rows={8}
                  className="w-full mt-1 px-3 py-2 border border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-950 text-slate-800 dark:text-slate-200 text-sm rounded-xl focus:outline-none font-mono resize-none"
                />
              </div>
            </div>
          )}
        </div>

        {/* Output Column */}
        <div className="lg:col-span-5 flex flex-col justify-between p-5 bg-slate-50 dark:bg-slate-950/40 rounded-2xl border border-slate-100 dark:border-slate-800">
          <div className="space-y-4">
            <div className="flex justify-between items-center">
              <span className="text-xs font-bold uppercase tracking-wider text-slate-400">Generated Code</span>
              <button
                onClick={copyOutput}
                className="text-xs font-semibold text-blue-600 dark:text-blue-400 flex items-center gap-1 hover:underline cursor-pointer"
              >
                <LucideIcon name="Copy" size={12} /> Copy Code
              </button>
            </div>

            <textarea
              readOnly
              value={outputText}
              rows={12}
              className="w-full p-4 rounded-xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 text-slate-800 dark:text-slate-200 font-mono text-xs leading-relaxed resize-none focus:outline-none"
            />
          </div>

          <button
            onClick={downloadTextFile}
            className="w-full mt-4 flex items-center justify-center gap-2 py-3 px-4 rounded-xl bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-700 hover:to-indigo-700 text-white font-medium shadow-lg hover:shadow-blue-500/10 transition-colors cursor-pointer"
          >
            <LucideIcon name="Download" size={18} /> Download Code File
          </button>
        </div>

      </div>
    </div>
  );
};
